name: Trigger Chromatic CI from comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger-chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI chromatic pipeline
        run: |
          curl -X POST https://circleci.com/api/v2/project/gh/Planingo/bubble-craft/pipeline \
            -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"branch\": \"${{ github.event.issue.pull_request.head.ref }}\", \"parameters\": {\"run_chromatic\": true}}"
